spring:
  application:
    name: transporteur-management
  data:
    mongodb:
      host: localhost
      port: 27017
      database: transporteur_db
      auto-index-creation: true

server:
  port: 8081

jwt:
  secret: mySecretKeyForJWTTokenGenerationAndValidationPleaseChangeInProduction
  expiration: 86400000
  issuer: transporteur-api

logging:
  level:
    root: INFO
    com.transporteur: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
